theme: jekyll-theme-minimal
title: Umut Ay Bora
logo: /assets/img/logo.png
description: Software Automation Engineer _[Email](mailto:umutaybora@gmail.com) / [LinkedIn](https://www.linkedin.com/in/umutayb/) / [GitHub](https://github.com/Umutayb)_
show_downloads: true
