plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
remote_theme: BDHU/minimalisttitle: Umut Ay Bora
logo: /assets/img/logo.png
description: Software automation at its finest. 
show_downloads: true
color-scheme: dark

github: [metadata]
