theme: jekyll-theme-minimal
title: Umut Ay Bora
logo: /assets/img/logo.png
description: My main objective is to reduce costs of certain tasks by automating them as efficiently as possible. I believe automation is necessary not just for testing but for any task that can benefit from it, and I am up to the task. Programming is one of my greatest passions, thus one of my biggest objectives is to improve my programming skills as much as possible. I excel at developing automation software that are easy to maintain, highly sustainable & efficient in execution. 
show_downloads: true
